-- USUÁRIOS E PRIVILÉGIOS

CREATE USER IF NOT EXISTS 'WEB_CLIENT'@'localhost' IDENTIFIED BY 'Lmxy20#a';
GRANT SELECT ON BuyPy.* TO 'WEB_CLIENT'@'localhost';

CREATE USER IF NOT EXISTS 'Wilson'@'localhost' IDENTIFIED BY 'Lmxy20#a';
GRANT ALL PRIVILEGES ON BuyPy.* TO 'Wilson'@'localhost';

CREATE USER IF NOT EXISTS 'BUYDB_OPERATOR'@'localhost' IDENTIFIED BY 'Lmxy20#a';
CREATE USER IF NOT EXISTS 'BUYDB_ADMIN'@'localhost' IDENTIFIED BY 'Lmxy20#a';

GRANT SELECT, INSERT, UPDATE, DELETE ON BuyPy.* TO 'BUYDB_OPERATOR'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.CreateOrder TO 'BUYDB_OPERATOR'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.GetOrderTotal TO 'BUYDB_OPERATOR'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.AddProductToOrder TO 'BUYDB_OPERATOR'@'localhost';

GRANT ALL PRIVILEGES ON BuyPy.* TO 'BUYDB_ADMIN'@'localhost' WITH GRANT OPTION;

GRANT SELECT ON BuyPy.* TO 'WEB_CLIENT'@'localhost';
GRANT INSERT, UPDATE ON Cliente TO 'WEB_CLIENT'@'localhost';
GRANT INSERT, UPDATE, DELETE ON Encomenda TO 'WEB_CLIENT'@'localhost';
GRANT INSERT, UPDATE, DELETE ON ItemEncomenda TO 'WEB_CLIENT'@'localhost';
GRANT UPDATE (quantidade) ON Produto TO 'WEB_CLIENT'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.CreateOrder TO 'WEB_CLIENT'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.GetOrderTotal TO 'WEB_CLIENT'@'localhost';
GRANT EXECUTE ON PROCEDURE BuyPy.AddProductToOrder TO 'WEB_CLIENT'@'localhost';

REVOKE ALL PRIVILEGES ON BuyPy.* FROM 'WEB_CLIENT'@'localhost';

FLUSH PRIVILEGES;
